export interface Product {
  id: string
  name: string
  price: number
  originalPrice?: number
  category: string
  categorySlug: string
  image: string
  images: string[]
  description: string
  details: string[]
  sizes: string[]
  colors: string[]
  colorHex: string[]
  isNew?: boolean
  isFeatured?: boolean
  isSale?: boolean
  loyaltyPoints: number
  stock: number
  rating: number
  reviews: number
  tags: string[]
}

export const categories = [
  { name: 'Tout', slug: 'all' },
  { name: 'Robes', slug: 'robes' },
  { name: 'Vestes', slug: 'vestes' },
  { name: 'Pantalons', slug: 'pantalons' },
  { name: 'Tops', slug: 'tops' },
  { name: 'Accessoires', slug: 'accessoires' },
]

export const products: Product[] = [
  {
    id: '1',
    name: 'Veste Oversize Structurée',
    price: 189,
    originalPrice: 249,
    category: 'Vestes',
    categorySlug: 'vestes',
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Une veste oversize au design architectural qui redéfinit les codes de la mode urbaine. Coupe structurée, épaules tombantes, finitions couturière.',
    details: ['100% Laine vierge', 'Doublure polyester recyclé', 'Fabriqué en France', 'Nettoyage à sec recommandé'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Noir', 'Ivoire', 'Camel'],
    colorHex: ['#111111', '#F5F0E8', '#C4A882'],
    isNew: true,
    isSale: true,
    loyaltyPoints: 189,
    stock: 12,
    rating: 4.8,
    reviews: 34,
    tags: ['oversize', 'automne', 'workwear'],
  },
  {
    id: '2',
    name: 'Robe Asymétrique Fluide',
    price: 145,
    category: 'Robes',
    categorySlug: 'robes',
    image: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Robe en crêpe fluide à ourlet asymétrique. Coupe minimaliste et élégante pour un effet sophistiqué sans effort.',
    details: ['Crêpe 95% viscose, 5% élasthane', 'Fermeture zip invisible', 'Fabrication européenne'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Noir', 'Bordeaux', 'Kaki'],
    colorHex: ['#111111', '#6B2D3A', '#5C5A3A'],
    isNew: true,
    isFeatured: true,
    loyaltyPoints: 145,
    stock: 8,
    rating: 4.9,
    reviews: 57,
    tags: ['robe', 'soirée', 'minimaliste'],
  },
  {
    id: '3',
    name: 'Pantalon Wide Leg Tailleur',
    price: 129,
    category: 'Pantalons',
    categorySlug: 'pantalons',
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4bedd4?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1594938298603-c8148c4bedd4?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Pantalon wide leg à taille haute en tissu de tailleur. Le basique ultime revisité avec une silhouette power.',
    details: ['Tissu stretch premium', 'Taille élastiquée', 'Poches fonctionnelles'],
    sizes: ['34', '36', '38', '40', '42', '44'],
    colors: ['Noir', 'Blanc', 'Taupe'],
    colorHex: ['#111111', '#FAFAF8', '#B8AFA0'],
    isFeatured: true,
    loyaltyPoints: 129,
    stock: 20,
    rating: 4.7,
    reviews: 42,
    tags: ['pantalon', 'tailleur', 'officewear'],
  },
  {
    id: '4',
    name: 'Manteau Capsule Ceinturé',
    price: 315,
    category: 'Vestes',
    categorySlug: 'vestes',
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Le manteau statement de la saison. Silhouette sculptée, ceinture double-face, col croisé. Une pièce capsule qui dure.',
    details: ['Lainage 80% laine', 'Doublure soie', 'Boutons en corne naturelle', 'Made in Italy'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Camel', 'Noir', 'Gris'],
    colorHex: ['#C4A882', '#111111', '#888888'],
    isFeatured: true,
    loyaltyPoints: 315,
    stock: 6,
    rating: 5.0,
    reviews: 19,
    tags: ['manteau', 'luxe', 'capsule'],
  },
  {
    id: '5',
    name: 'Top Brassière Sculptant',
    price: 69,
    category: 'Tops',
    categorySlug: 'tops',
    image: 'https://images.unsplash.com/photo-1583744946564-b52ac1c389c8?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1583744946564-b52ac1c389c8?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Brassière à bonnets souples en jersey technique. Confort maximal, maintien parfait, esthétique sport-luxe.',
    details: ['Jersey 88% polyamide recyclé, 12% élasthane', 'Bretelles ajustables', 'Bonnets amovibles'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Noir', 'Blanc', 'Nude', 'Rouge'],
    colorHex: ['#111111', '#FAFAF8', '#E8C9B0', '#C0392B'],
    isNew: true,
    loyaltyPoints: 69,
    stock: 30,
    rating: 4.6,
    reviews: 88,
    tags: ['sport-luxe', 'brassière', 'été'],
  },
  {
    id: '6',
    name: 'Sac Minaudière Chaîne',
    price: 95,
    category: 'Accessoires',
    categorySlug: 'accessoires',
    image: 'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Minaudière en cuir vegan avec chaîne dorée amovible. Du jour au soir, elle s\'adapte à chaque silhouette.',
    details: ['Cuir vegan certifié', 'Chaîne dorée 24K plaquée or', 'Fermeture magnétique', 'Livré avec pochon'],
    sizes: ['Unique'],
    colors: ['Noir', 'Cognac', 'Blanc Cassé'],
    colorHex: ['#111111', '#8B5A2B', '#F5F0E8'],
    isNew: true,
    loyaltyPoints: 95,
    stock: 15,
    rating: 4.8,
    reviews: 63,
    tags: ['sac', 'soirée', 'accessoire'],
  },
  {
    id: '7',
    name: 'Chemise Oversized Texturée',
    price: 98,
    originalPrice: 128,
    category: 'Tops',
    categorySlug: 'tops',
    image: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Chemise oversize en tissu texturé à rayures ton sur ton. Portée ouverte sur un top ou boutonnée, elle impose son style.',
    details: ['100% coton organique', 'Col classique', 'Poches poitrine'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Blanc', 'Bleu Ciel', 'Noir'],
    colorHex: ['#FAFAF8', '#87CEEB', '#111111'],
    isSale: true,
    loyaltyPoints: 98,
    stock: 18,
    rating: 4.5,
    reviews: 31,
    tags: ['chemise', 'coton', 'casual'],
  },
  {
    id: '8',
    name: 'Robe Bandage Latex Effect',
    price: 175,
    category: 'Robes',
    categorySlug: 'robes',
    image: 'https://images.unsplash.com/photo-1487222477894-8943e31ef7b2?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1487222477894-8943e31ef7b2?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Robe moulante effet latex à l\'esthétique avant-gardiste. Matière innovante stretch, confort surprenant, impact visuel maximal.',
    details: ['Tissu technique stretch', 'Doublure intégrée', 'Zip invisible dos', 'Lavage délicat'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Noir', 'Rouge', 'Blanc'],
    colorHex: ['#111111', '#C0392B', '#FAFAF8'],
    isNew: true,
    isFeatured: true,
    loyaltyPoints: 175,
    stock: 9,
    rating: 4.9,
    reviews: 22,
    tags: ['club', 'statement', 'soirée'],
  },
  {
    id: '9',
    name: 'Jean Barrel Délavé',
    price: 119,
    category: 'Pantalons',
    categorySlug: 'pantalons',
    image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Jean barrel à taille haute, coupe tonneau et délavage vintage. La pièce denim de la saison.',
    details: ['Denim 98% coton, 2% élasthane', 'Délavage artisanal', '5 poches', 'Fabriqué au Portugal'],
    sizes: ['34', '36', '38', '40', '42'],
    colors: ['Bleu Délavé', 'Noir Délavé', 'Gris'],
    colorHex: ['#7CA3C5', '#2A2A2A', '#888888'],
    loyaltyPoints: 119,
    stock: 25,
    rating: 4.7,
    reviews: 76,
    tags: ['denim', 'vintage', 'casual'],
  },
  {
    id: '10',
    name: 'Bottines Chelsea Premium',
    price: 225,
    category: 'Accessoires',
    categorySlug: 'accessoires',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Bottines Chelsea en cuir pleine fleur, semelle track crantée. L\'alliance du classique et du street.',
    details: ['Cuir pleine fleur', 'Semelle caoutchouc recyclé', 'Élastiques intégrés', 'Semelle intérieure cuir'],
    sizes: ['36', '37', '38', '39', '40', '41'],
    colors: ['Noir', 'Cognac'],
    colorHex: ['#111111', '#8B5A2B'],
    isFeatured: true,
    loyaltyPoints: 225,
    stock: 7,
    rating: 4.9,
    reviews: 48,
    tags: ['chaussures', 'cuir', 'capsule'],
  },
  {
    id: '11',
    name: 'Blazer Croisé Satiné',
    price: 215,
    originalPrice: 265,
    category: 'Vestes',
    categorySlug: 'vestes',
    image: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Blazer croisé en tissu satiné à reflets. Revers larges, coupe cintrée, boutons bijoux. De jour comme de nuit.',
    details: ['Polyester satiné haute densité', 'Coupe ajustée', 'Boutons bijoux', 'Poche poitrine'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Noir', 'Ivoire', 'Champagne'],
    colorHex: ['#111111', '#F5F0E8', '#E8D5A0'],
    isSale: true,
    loyaltyPoints: 215,
    stock: 11,
    rating: 4.8,
    reviews: 29,
    tags: ['blazer', 'luxe', 'soirée'],
  },
  {
    id: '12',
    name: 'Ceinture Corset XXL',
    price: 55,
    category: 'Accessoires',
    categorySlug: 'accessoires',
    image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Ceinture corset large en cuir vegan à laçage réglable. Transforme n\'importe quelle tenue en statement look.',
    details: ['Cuir vegan', 'Largeur 12 cm', 'Laçage ajustable', 'Boucle métallique dorée'],
    sizes: ['S/M', 'M/L', 'L/XL'],
    colors: ['Noir', 'Cognac', 'Blanc'],
    colorHex: ['#111111', '#8B5A2B', '#FAFAF8'],
    isNew: true,
    loyaltyPoints: 55,
    stock: 22,
    rating: 4.6,
    reviews: 41,
    tags: ['ceinture', 'accessoire', 'corset'],
  },
]

export const getFeatured = () => products.filter(p => p.isFeatured)
export const getNew = () => products.filter(p => p.isNew)
export const getSale = () => products.filter(p => p.isSale)
export const getByCategory = (slug: string) =>
  slug === 'all' ? products : products.filter(p => p.categorySlug === slug)
export const getById = (id: string) => products.find(p => p.id === id)
